# Generated by Django 4.0.2 on 2022-02-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LetterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус письма')),
            ],
            options={
                'verbose_name': 'Статус письма',
                'verbose_name_plural': 'Статусы писем',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LineContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(db_index=True, max_length=127, verbose_name='Наименование изделия')),
                ('enter_number', models.CharField(max_length=127, verbose_name='Входящий номер')),
                ('request_date', models.DateField(verbose_name='Дата заявки')),
                ('customer_out_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='Исходящий номер заказчика')),
                ('customer_out_date', models.DateField(blank=True, null=True, verbose_name='Дата исходящего письма заказчика')),
                ('customer_phone', models.CharField(blank=True, max_length=127, null=True, verbose_name='Телефон заказчика')),
                ('official_memo', models.CharField(blank=True, max_length=127, null=True, verbose_name='Служебная записка')),
                ('official_memo_date', models.DateField(blank=True, null=True, verbose_name='Дата СЗ')),
                ('personal_time', models.FloatField(blank=True, null=True, verbose_name='Время занятости персонала')),
                ('personal_time_spz', models.FloatField(blank=True, null=True, verbose_name='Время занятости согл. ШПЗ')),
                ('personal_time_vp', models.FloatField(blank=True, null=True, verbose_name='Время занятости согл. ВП')),
                ('expected_test_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата испытания')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='Дата оповещения')),
                ('notification_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Заказчик')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
                ('expected_cost', models.FloatField(blank=True, null=True, verbose_name='Ориентировочная стоимость (руб)')),
                ('fact_cost', models.FloatField(blank=True, null=True, verbose_name='Фактическая стоимость (руб)')),
                ('bill', models.CharField(blank=True, max_length=127, null=True, verbose_name='Договор (Счет)')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('bill_date_signing', models.DateField(blank=True, null=True, verbose_name='Дата подписания договора')),
                ('bill_date_final', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('in_gov_contract_from', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('price_protocol', models.CharField(blank=True, max_length=127, null=True, verbose_name='Протокол согласования цены/с/з о цене')),
                ('RKM_request', models.CharField(blank=True, max_length=127, null=True, verbose_name='Запрос ОЦО в 146 ВП о предоставлении РКМ ')),
                ('deal_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='№ папки/дела')),
                ('price_letter_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='Наше исходящее письмо о цене')),
                ('out_letter_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='№ нашего исх. (об отправке договорного документа)')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки договорного документа')),
                ('bill_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='№  счета на оплату')),
                ('pay_bill_date', models.DateField(blank=True, null=True, verbose_name='Дата счета на оплату')),
                ('pp_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='№ П/П')),
                ('pp_date', models.DateField(blank=True, null=True, verbose_name='Дата П/П')),
                ('service_act_number', models.CharField(blank=True, max_length=127, null=True, verbose_name='№ акта оказанных услуг')),
                ('service_act_date', models.DateField(blank=True, null=True, verbose_name='Дата акта оказанных услуг')),
                ('bill_facture', models.CharField(blank=True, max_length=127, null=True, verbose_name='Счет-фактура')),
                ('bill_facture_date', models.DateField(blank=True, null=True, verbose_name='Дата счет-фактуры')),
                ('spz', models.CharField(blank=True, max_length=127, null=True, verbose_name='ШПЗ')),
                ('spz_date', models.DateField(blank=True, null=True, verbose_name='Срок действия ШПЗ')),
                ('comment_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за заявку')),
                ('full_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='full_status', to='contract.category', verbose_name='Статус всей заявки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.organization', verbose_name='Вид испытаний')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.category', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Номер письма')),
                ('date', models.DateField(verbose_name='Дата письма')),
                ('letter_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.letterstatus', verbose_name='Статус письма')),
                ('line_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.linecontract')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['line_contract'],
            },
        ),
    ]
