# Generated by Django 4.0.2 on 2022-03-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecontract',
            name='RKM_request',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Запрос ОЦО в 146 ВП о предоставлении РКМ'),
        ),
        migrations.AlterField(
            model_name='linecontract',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Контакты заказчика'),
        ),
        migrations.AlterField(
            model_name='linecontract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='linecontract',
            name='price_protocol',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Протокол согласования цены/ с/з о цене'),
        ),
        migrations.AlterField(
            model_name='linecontract',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.category', verbose_name='Статус испытаний'),
        ),
    ]
