# Generated by Django 4.0.2 on 2022-03-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_linecontract_rkm_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='line_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.linecontract', verbose_name='Договор'),
        ),
    ]
