# Generated by Django 4.0.2 on 2022-02-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Испытательное оборудование')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Заводской номер')),
            ],
            options={
                'verbose_name': 'Испытательное оборудование',
                'verbose_name_plural': 'Испытательное оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Режим',
                'verbose_name_plural': 'Режимы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Вид испытаний')),
            ],
            options={
                'verbose_name': 'Вид испытаний',
                'verbose_name_plural': 'Вид испытаний',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255, verbose_name='Тип изделия')),
                ('device_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('dec_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Децимальный номер')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_start', models.DateField(verbose_name='Дата начала испытаний')),
                ('date_stop_expected', models.DateField(verbose_name='Ожидаемая дата завершения')),
                ('date_stop', models.DateField(blank=True, null=True, verbose_name='Дата завершения испытаний')),
                ('act_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('act', models.FileField(blank=True, null=True, upload_to='acts/', verbose_name='Акт')),
                ('programm', models.FileField(blank=True, null=True, upload_to='programms/', verbose_name='Программа')),
                ('cats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Статус')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.testtype', verbose_name='Вид испытаний')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата включения')),
                ('date_stop', models.DateField(verbose_name='Дата выключения')),
                ('work_time', models.IntegerField(verbose_name='Время работы')),
                ('eq_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.equipment', verbose_name='Оборудование')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('line_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.linecontract')),
                ('line_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.line')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mode', verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Наработка',
                'verbose_name_plural': 'Наработка',
                'ordering': ['eq_name'],
            },
        ),
    ]
