# Generated by Django 4.0.2 on 2022-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='characters',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Характеристики'),
        ),
    ]
