# Generated by Django 4.0.2 on 2022-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mode_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='characters',
        ),
        migrations.AddField(
            model_name='equipmentwork',
            name='mode_specific',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристики режима'),
        ),
    ]
