# Generated by Django 4.0.2 on 2022-03-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_letters_line_contract'),
        ('main', '0004_remove_equipmentwork_mode_specific_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['order_number'], 'verbose_name': 'Испытательное оборудование', 'verbose_name_plural': 'Испытательное оборудование'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='order_number',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipmentwork',
            name='line_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.linecontract', verbose_name='Договорное испытание'),
        ),
    ]
